### ISSUE TITLE
如何得出矩形框

### ISSUE THREAD

**Issue by zouxiaoshi** [zonasw/DBNet#10]
如题，您好，如何从多边形得到矩形？

**Comment by Lebron-Harden** [comment]
在inference.py中的main函数中可以这样写
        for box in boxes:
            #根据轮廓的坐标，绘制矩形框
            (x,y,w,h) = cv2.boundingRect(np.array(box))
            cv2.rectangle(src_image,(x,y),(x+w,y+h),(0,0,255),2)
            #cv2.drawContours(src_image, [np.array(box)], -1, (0, 255, 0), 2)

**Comment by zouxiaoshi** [comment]
> 在inference.py中的main函数中可以这样写
> for box in boxes:
> #根据轮廓的坐标，绘制矩形框
> (x,y,w,h) = cv2.boundingRect(np.array(box))
> cv2.rectangle(src_image,(x,y),(x+w,y+h),(0,0,255),2)
> #cv2.drawContours(src_image, [np.array(box)], -1, (0, 255, 0), 2)

多谢，老铁。
