### ISSUE TITLE
which dataset was used?

### ISSUE THREAD

**Issue by littleforce163** [zonasw/DBNet#3]
Hi,
There are lots of dataset, which one was used for train?

```
 icdar2015
 MLT2019
 COCO-Text_v2
 ReCTS
 SROIE
 ArT
 LSVT
 Synth800k
 icdar2017rctw
 MTWI 2018
 百度中文场景文字识别
 mjsynth
 Synthetic Chinese String Dataset(360万中文数据集)
 英文识别数据大礼包
```

**Comment by zonasw** [comment]
> Hi,
> There are lots of dataset, which one was used for train?
> 
> ```
>  icdar2015
>  MLT2019
>  COCO-Text_v2
>  ReCTS
>  SROIE
>  ArT
>  LSVT
>  Synth800k
>  icdar2017rctw
>  MTWI 2018
>  百度中文场景文字识别
>  mjsynth
>  Synthetic Chinese String Dataset(360万中文数据集)
>  英文识别数据大礼包
> ```

I only used some of the data, and I can't remember which ones. Soon I'll be training with all the data sets.
U can also try to train with all the data, and u r welcome to submit PR.

**Comment by EarthLikeDream** [comment]
good
