### ISSUE TITLE
which label tool you use?

### ISSUE THREAD

**Issue by lc2313445** [zonasw/DBNet#4]
Hi, may I ask which label tool you use? cause I want to label my own image~

**Comment by zonasw** [comment]
> Hi, may I ask which label tool you use? cause I want to label my own image~

U can annotate your images using `labelme`
U can install it using the following command `pip install labelme`
U need 2 use a conversion tool to convert the annotated results into a format that you can use directly, The location of the tool is `datatools/labelme2data.py`

**Comment by lc2313445** [comment]
^-^Thank you very much, I just write a script to transfer labelme data type to yours'...I would have waited if I had known you can provide the tool for us.
